### ISSUE TITLE
【課題】取得済みtweet過去投稿データの重複取得を避ける方法

### ISSUE THREAD

**Issue by great084** [great084/twitter_tool#14]
DBに格納済みの、Twitterの過去投稿データと、取得しようとする範囲（期間指定）に
重複がある場合、重複して取得することを避ける方法を決める必要がある。

- [ ] Twitter APIで過去投稿データを取得する際に、指定できるクエリ条件を確認する
- [ ] 指定できるクエリ条件と、アプリ内で保持するデータ内容で、APIでのデータ取得対象から重複を回避できるか検討する
- [ ] 上記難しければ、データ取得対象には含めるが、DB書き込み時に上書き制御するなどの方針とする

※APIには取得レート制限があるため、できるだけ過去に取得してDBに保存しているデータは、取得対象から外して効率的に枠を使うほうが望ましい。

**Comment by great084** [comment]
@domi10momo 

nextトークンを利用して以下の方法で重複取得の回避を実現したいです。
実装ついて検討いただけないでしょうか？

### おおまかな処理の流れ
・ツイート保存画面で件数を指定(ex. 200件）してデータ取得
・画面から指定した件数(200件）に達した場合で、かつTwitter APIの戻り値にnextトークンが存在する場合、クエリ内容と、nextトークンの内容をシステムに保存。
・クエリ内容・nextトークンが存在する場合、次回ツイート保存画面を起動した場合、「前回の続きから取得する」という選択肢（ボタンなど）を表示する。
・「前回の続きから取得する」を選択された場合、保存したクエリ、nextトークンを利用してAPでツイートデータIを取得する。
・保存したクエリ、nextトークンを削除（論理削除）する

・以降繰り返し

**Comment by domi10momo** [comment]
@great084
ありがとうございます。2点質問があります。
1. 継続で使用するクエリは１番最後のクエリのみ　という認識で良いか
2. 保存したクエリを論理削除すると書いてありますが、sessionではなくテーブルを使用して実装するのか？

論理削除ではなく、sessionの上書きでデータを更新しているのですが、テーブルに保存して論理削除の方がよろしいでしょうか。ご確認お願い致します。
