### ISSUE TITLE
開発補助ツール(gem)を洗い出す

### ISSUE THREAD

**Issue by great084** [great084/twitter_tool#4]
## 概要
円滑な開発に役立つ開発補助のgemを調査し、導入するものを決める

## 内容
必要と思われるもの
- コーディングの自動チェック機能
- デバッグツール
- テストライブラリ
- modelにDB定義を書き込む
などなど、

過去の共同開発やポートフォリオ開発などで利用して、便利だったものから選定すると良い

**Comment by nakamitsu-nozomi** [comment]
## 必要と思われる開発補助ツール(gem)
- コーディングの自動チェック機能
  - `Rubocop`
- デバッグツール
  - `pry-byebug`
  - `pty-rails`
  - `pry-doc`
- テストライブラリ
  - `Rspec`
- modelにDB定義を書き込む
  - `annotate`
- ログイン機能
  - `devise`
- 日本語化
  - `rails-i18n`
  - `devise-i18n`

## その他必要そうなこと
- bootstrapの追加

##  参考資料
- 逆転教材　
  - (https://arcane-gorge-21903.herokuapp.com/)
- 　Qiita「Rails new ⇒ 必須の設定 を3秒で済ます」
  - (https://qiita.com/naoki_mochizuki/items/791c46c8572bf754ec22)

**Comment by great084** [comment]
@nakamitsu-nozomi 
確認しました！
開発補助のツールとしては良いと思います。

機能として必要なライブラリ(devise, bootstrapなど)については、仕様を決めた際に再度必要なものを洗い出しましょう。

**Comment by nakamitsu-nozomi** [comment]
issuegを完了致しました。
