### ISSUE TITLE
Railsプロジェクトを作成し、githubにプッシュする

### ISSUE THREAD

**Issue by great084** [great084/twitter_tool#5]
## 概要
Railsアプリを作成し，masterブランチにプッシュする

## 内容
条件は以下、バージョンなどは最新版に更新する
- Ruby 2.6.6  
- Rails 6.0.3.1  
- Bundler は ver 2 を使用
- データベースはPostgreSQL
- MiniTestとCoffeeScriptは使わない
- `.gitignore` を修正（.DS_Storeなどを追加）

※参考のコマンド
```
rails new XXXXXXX -d postgresql -T --skip-coffee
```

https://github.com/rails/rails/blob/master/.gitignore

**Comment by nakamitsu-nozomi** [comment]
issueを完了致しました。
