### ISSUE TITLE
ツイートの取得ができない。

### ISSUE THREAD

**Issue by nakamitsu-nozomi** [great084/twitter_tool#60]
## バグの現象
再投稿機能の修正をしていた際に遭遇したバグです。
保存一覧ページから、過去ツイートの取得ができません。（feature/tweetブランチだけでなく、全てのブランチで取得作業ができないです）
画像のようにエラーが出ます。

<img width="1440" alt="スクリーンショット 2020-12-20 15 11 31" src="https://user-images.githubusercontent.com/67478234/102707045-b7452d80-42da-11eb-894b-edafec6780c4.png">
ターミナル上

```
  Parameters: {"authenticity_token"=>"文字列", "period"=>"until_now", "commit"=>"取得する"}
Unpermitted parameters: :authenticity_token, :commit

```
### 本来あるべき動作
ツイートの取得ができる。
### 実際の動作
ログインはできる。
過去ツイートの取得ができない。
再投稿ツイートはできる。

## バグの原因

@ひろみちさん指摘箇所 は修正済です。

```
    def response_data_nil?(response)
      !!if response["results"].empty?
          redirect_to new_tweet_path, flash: { alert: "指定した期間内にデータはありませんでした。" }
        end
    end
```
おそらく、原因がわからず困ってます。全てのブランチにバグが怒っているということは、.env や私のアカウントに問題あるのかなと思ったのですが、.env の下記は正しいものでした。キーの変更もしてません。
TWITTER_API_KEY 
TWITTER_API_SECRET
TWITTER_ACCESS_TOKEN 
ACCESS_TOKEN_SECRET 
BEARER_TOKEN 

どのように対処すべきかわからず困ってます。アドバイスお願い致します。

https://github.com/great084/twitter_tool/pull/51

**Comment by great084** [comment]
@nakamitsu-nozomi 

>保存一覧ページから、過去ツイートの取得ができません。（feature/tweetブランチだけでなく、全てのブランチで取得作業ができないです）

過去ツイートの取得が全くできないということでしょうか？
また全てのブランチというのはmasterブランチでも同様のエラーが出るということでしょうか？

まずは、デバッグモードにして、エラーが出る直前の部分のresponseの内容を確認してもらえますか？
