### ISSUE TITLE
[機能追加]リツイート、再投稿した日時を表示させる

### ISSUE THREAD

**Issue by great084** [great084/twitter_tool#67]
## 概要

ツイートに対して、リツイート、再投稿を行った場合、現状【済】を表示するだけだが、
一定時間経過後、再度リツイート、再投稿を行うことを想定して、
ツイート詳細画面でリツイート、再投稿した日時を表示させる

## 実装内容

- [x] ワイヤーフレームの修正

- [x] table構成の検討 ER−図の修正
※1つのツイートに対して、複数回の再投稿、リツイートが行われた場合を踏まえて検討すること

- [x] 実装

**Comment by domi10momo** [comment]
タスクを実行するにあたり、ワイヤフレームの修正。テーブル、ER図の修正を行いました。
方向性間違いないでしょうか。ご確認いただければ幸いです。

[wikiドキュメント ](https://github.com/great084/twitter_tool/wiki/%E5%90%84%E7%A8%AE%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88)

**Comment by great084** [comment]
@domi10momo 
テーブル、ER-図は良いと思います。ちなみに、redraftよりrepostのほうがしっくり来るような・・

あと、リツイート、再投稿の日時の表示は詳細画面です。
一覧画面は現状のまま有り無しのみで、詳細で日時を履歴スタイルで表示できればと思います。
>ツイート詳細画面でリツイート、再投稿した日時を表示させる

**Comment by domi10momo** [comment]
@great084 
ご確認ありがとうございます。修正しました。
