### ISSUE TITLE
Twitter developerアカウントの取得

### ISSUE THREAD

**Issue by great084** [great084/twitter_tool#7]
## 概要
Twitter APIを利用するために、developerアカウントを取得する
プランはpremium(sandbox)。

他のメンバが、アカウント取得する際の参考にできるように、アカウント取得の手順をwikiに掲載する

**Comment by domi10momo** [comment]
・Twitterのdeveloperアカウント取得完了(sandbox)
・wikiにアカウント取得手順の掲載
https://github.com/great084/twitter_tool/wiki/Twitter-Developer-%E7%94%B3%E8%AB%8B

<br>
デベロッパー画面<br>

<img width="1261" alt="searchAPI_sandbox画面" src="https://user-images.githubusercontent.com/35606852/98462597-ce333300-21f8-11eb-83fe-3f177f1ad699.png">
