### ISSUE TITLE
機能追加のライブラリ（gem, js)の洗い出し

### ISSUE THREAD

**Issue by great084** [great084/twitter_tool#8]
## 概要
機能追加のために必要なgem、javascriptライブラリを調査し、導入するものを決める

## 内容
必要と思われるもの

- ログイン機能 (twitter認証を含む）
- 環境変数管理(twitter アクセストークンを安全に管理するためのもの）
- UIフレームワーク（Bootstrap）
- ページネーション機能
- twitter API連携機能
- 日本語化

## アウトプット
調査結果をwikiに記載する

**Comment by nakamitsu-nozomi** [comment]
2020/11/08　`機能追加のライブラリ（gem, js)の洗い出し` 完了
